# -*- coding: utf-8 -*-
"""exercícios_phyton

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PnXHWNSrb64Iu2XNydUeCoyOufhPy5U4
"""

#variaveis e seus tipos
x = 10
nome = ' aluno'
nota = 5.5
fez_inscricao = True

#exibindo o tipo da variavel

print (type(x))
print (type(nome))
print (type(nota))
print (type(fez_inscricao))

nome = input ("Digite seu nome")
#forma de mostrar uma string da variavel input
print (f"Ola {nome} esse foi seu primeiro codigo de phyton" )

Nota_1 = int(input("Digite a primeira nota"))
Nota_2 = int(input("Diginte a segunda nota"))
Nota_3 = int(input("Digite a terceira nota"))
Nota_4 = int(input("Digite a quarta nota"))

media = (Nota_1+Nota_2+Nota_3+Nota_4)/4

if media >= 6:
      situacao = "aprovado"

else:
      situacao = "reprovado"

print (f"A sua nota foi : {media}")
print (f" situação do aluno é : {situacao}")

#condições

idade = int(input("digite sua idade")) #variavel que vai perguntar e armazenar o um numero inteiro que é a idade

#função/condição para validar o valor armazenado e dar um retorno
if idade < 18 :
  print("Voce ainda é de menor estude para ser rico")
elif idade >= 18 and idade < 65:
    print("Voce ja é Adulto forme uma bela familia")
else :
  print("Voce ja é idoso chegou a level açto do game")

idade = int(input("digite sua idade")) #variavel que vai perguntar e armazenar o um numero inteiro que é a idade


Filme_01 = "Filmes infantil"
Filme_02 = "Filmes Adolescentes"
Filme_03 = "Pode assistir qualquer categoria de filmes"



#função/condição para validar o valor armazenado e dar um retorno
if idade < 12 :
  print(f"Voce ainda é de menor estude então tem direito a assistir {Filme_01}")
elif idade >= 12 and idade < 18:
    print(f"sua idade so permite que pode assistir {Filme_02}")
else :
  print(f"Voce ja é Adulto {Filme_03}")

#Repetição por quantidade

for x in range(5):
 print (x)

for y in range (2,7): #loop começa no 2 e termina 7 mais o 7 não entra
  print (y)

for z in range(1,11, 2):# o loop começa no 1 e termina no 11 pulando dois nomero
  print (z)

for numero in range(1,11):
  if numero % 2 == 0: #quando a divisão do (numero) por 2 for igual a 0 o codigo para e mostra o valor
    print("o primeiro numero par encontrado foi:", numero)
    break


    #verifica o primeiro numero par

for numero in range (1,10):
  if numero == 5:  # quando a variavel numero for igual a 5 o codigo vai continuar rodando
    continue
  print(numero)

#sistema de avaliação de filnmes

filmes = ["filme 1", "filme 2", "filme 3"]

print("Bem vindo a classificação de filmes")
print("Vocen tem tres filmes para avaliar")
print("Digite 0 para parar a qualquer momento")

for filme in filmes:
  classificacao = int(input(f"Digite uma nota de 1 a 10 para classificar {filme} :"))
  if classificacao == 0:
    print("Obrigado por usar nossa sistema de avaliçao")
    break
  if classificacao < 1 or classificacao > 10:
        print("Por favor digite uma valor acima de 0 ou menor que 11")
  else:
      print(f"Voce classificou {filme} com {classificacao} estrelas")

print("Obrigado por usar nossa sistema de avaliçao")

